#!/bin/sh
set -e

# Check types in case did not npm run build (which runs tsc)
npm run type-check

# Check formatting
npx prettier --check .

# Run all unit tests to ensure no regressions (fail fast)
npm run test:unit
